// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiRVr1claaMdoIj_t5Idol85tDegAsdOM',
    appId: '1:615429591262:web:10af6ac5bd172418a6b24f',
    messagingSenderId: '615429591262',
    projectId: 'hex-project-3d7b1',
    authDomain: 'hex-project-3d7b1.firebaseapp.com',
    storageBucket: 'hex-project-3d7b1.appspot.com',
    measurementId: 'G-8VPT0HNEZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSvZ6tfjKPKgrUYhLIMtI_hrV77sS84g',
    appId: '1:615429591262:android:2a248ee246f88a34a6b24f',
    messagingSenderId: '615429591262',
    projectId: 'hex-project-3d7b1',
    storageBucket: 'hex-project-3d7b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_bKbCCLVA1Oepvd1UssIppO4SlhpP6Hg',
    appId: '1:615429591262:ios:075fe226f2114aeda6b24f',
    messagingSenderId: '615429591262',
    projectId: 'hex-project-3d7b1',
    storageBucket: 'hex-project-3d7b1.appspot.com',
    iosClientId: '615429591262-rp38uj9sdtmim4ifvi578gh20ogmiscd.apps.googleusercontent.com',
    iosBundleId: 'com.example.webStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_bKbCCLVA1Oepvd1UssIppO4SlhpP6Hg',
    appId: '1:615429591262:ios:0b884de30625b472a6b24f',
    messagingSenderId: '615429591262',
    projectId: 'hex-project-3d7b1',
    storageBucket: 'hex-project-3d7b1.appspot.com',
    iosClientId: '615429591262-q66ov0tmat0l5fve2ajneo8a8vl17tli.apps.googleusercontent.com',
    iosBundleId: 'com.example.webStart.RunnerTests',
  );
}
